Rms-Core-313/Rms-Core-313/Controllers/OnlineOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rms_Core_313.BLL.BLL;
using Rms_Core_313.BLL.Interface;
using Rms_Core_313.Model.Models;
using Rms_Core_313.Models;
using Rms_Core_313.Models.Vm;
using Stripe;
using Microsoft.AspNetCore.Identity;

namespace Rms_Core_313.Controllers
{
    public class OnlineOrderController : Controller
    {
        private readonly IOrderPlaceManager manager;
        private readonly IMapper _mapper;
      
        public OnlineOrderController(IOrderPlaceManager _manager, IMapper mapper)
        {
            manager = _manager;
            _mapper = mapper;
          
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult Create(OrderPlaceVm vm)
        {
            if (ModelState.IsValid && vm.OrderPlaceDetails != null && vm.ReciverPhone!= null)
            {
                OrderPlaceVm Order = new OrderPlaceVm();
                var entity = _mapper.Map<OrderPlace>(vm);
                entity.UserId = User.Identity.Name;
                entity.date = DateTime.Today;
                var data = manager.Create(entity);
                //vm.OrderPlaces = manager.GetOrderPlacesList();
                if (vm.IsCashOnDelivery == "on" && data == true)
                {

                    var quentity = 0;
                    var amount = 0.00;

                    foreach (var item in vm.OrderPlaceDetails)
                    {
                        //List<OrderPlaceDetails> i = manager.GetOrderPlacesById(List<long> Ids);
                        //name += item.menusCreate.Name + ",";
                        quentity += item.Quantity;
                        amount += (item.Quantity * item.Price);
                    }
                    return RedirectToAction("PaymentGetwayFeedback" );
                }
                else
                {

                    var quentity = 0;
                    var amount = 0.00;

                    foreach (var item in vm.OrderPlaceDetails)
                    {
                        //List<OrderPlaceDetails> i = manager.GetOrderPlacesById(List<long> Ids);
                        //name += item.menusCreate.Name + ",";
                        quentity += item.Quantity;
                        amount += (item.Quantity * item.Price);
                    }
                    return RedirectToAction("PaymentGetwayIntegrate", new { quantity = quentity, amount = amount });
                }

            }
            else
            {
                ViewBag.Validdata = false;
                return View();
            }
           
        }
        public ActionResult PaymentGetwayIntegrate(int quantity,int amount)
        {
            StripeSetting student = new StripeSetting { Quantity = quantity, Amount = amount};
            return View(student);
        }
        [HttpPost]
        public ActionResult PaymentGetwayIntegrate(string stripeEmail, string stripeToken)
        {
            var customers = new CustomerService();
            var charges = new ChargeService();

            var customer = customers.Create(new CustomerCreateOptions
            {
                Email = stripeEmail,
                Source = stripeToken
            });

            var charge = charges.Create(new ChargeCreateOptions
            {
                Amount = 500,
                Description = "Test Payment",
                Currency = "GBP",
                Customer = customer.Id,
                ReceiptEmail = stripeEmail,
                Metadata = new Dictionary<string, string>()
                {
                    {"OrderId","111"},
                    { "PostCode","E15NB"},
                }
            });

            if (charge.Status == "succeeded" || charge.Status == "pending" || charge.Status == "failed")
            {
                string BalanceTranjectionId = charge.BalanceTransactionId;
                return RedirectToAction("PaymentGetwayFeedback");
            }
            else
            {

            }
            return View();
        }
        [Authorize]
        public ActionResult PaymentGetwayFeedback()
        {
            var oData = new OrderPlace();
            var uData= manager.GetLatestIdByUser(User.Identity.Name);
            var sData=uData.LastOrDefault();
            oData.IsComplitePayment = true;
            oData.Id = sData.Id;
            manager.Update(oData);
            return View();
        }
        public ActionResult GetOrderList()
        {
            var order = new OrderPlaceVm();
            order.Email= manager.GetUserById(User.Identity.Name);
            order.OrderPlaces = manager.GetOrderPlacesList();
            return View(order);
        }

    }
}

Rms-Core-313/Rms-Core-313/Views/OnlineOrder/Create.cshtml
@using Microsoft.AspNetCore.Identity;
<style>
    .switch {
        position: relative;
        display: inline-block;
        width: 60px;
        height: 34px;
    }

        .switch input {
            opacity: 0;
            width: 0;
            height: 0;
        }

    .slider {
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #ccc;
        -webkit-transition: .4s;
        transition: .4s;
    }

        .slider:before {
            position: absolute;
            content: "";
            height: 26px;
            width: 26px;
            left: 4px;
            bottom: 4px;
            background-color: white;
            -webkit-transition: .4s;
            transition: .4s;
        }

    input:checked + .slider {
        background-color: #2196F3;
    }

    input:focus + .slider {
        box-shadow: 0 0 1px #2196F3;
    }

    input:checked + .slider:before {
        -webkit-transform: translateX(26px);
        -ms-transform: translateX(26px);
        transform: translateX(26px);
    }

    /* Rounded sliders */
    .slider.round {
        border-radius: 34px;
    }

        .slider.round:before {
            border-radius: 50%;
        }
</style>
<div>df</div>
<div>df</div>
<div>d</div>
<div></div>
<div></div>
@if (ViewBag.Validdata == false)
{
    <input type="hidden" id="viewbaddata" value="true" />
}
else
{
    <input type="hidden" id="viewbaddata" value="false" />
}
<div class="container" style=" margin-top:2%">
    <div class="row">
        <div class="col-md-8">

            <div class="alert alert alert-danger alert-dismissible fade in" role="alert" id="errorMsg" style="display: none">
                <strong>Sorry! </strong> You have to add a phone no on receiver phone!
            </div>
            <div class="vertical-tab" role="tabpanel">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs fixed-top" id="ul" role="tablist">
                    <li role="presentation"><a class="AllData" aria-controls="home" role="tab" data-toggle="tab">All Food</a></li>

                </ul>

                <!-- Tab panes -->
                <div class="tab-content tabs" id="mainlist">
                    <div role="tabpanel" class="tab-pane fade in active tabpanelData" id="tabpanelData">
                    </div>

                </div>
            </div>
        </div>
        <div class="col-md-4" style="background-color:#353b48">
            <div class="row">

                <h2 style="margin-left:20px;">Your Order</h2>
                <hr />
                <div class="control">

                </div>

                <table class="table">
                    <thead>
                    <th>Quantity</th>
                    <th>Dish</th>
                    <th>Price</th>
                    <th>Delete</th>
                    </thead>
                    <tbody id="placeOrder"></tbody>

                </table>

            </div>


        </div>
        <div>

        </div>
        @using (Html.BeginForm("Create", "OnlineOrder", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            <div id="footer" style="float:right"></div>
            <div id="HiddenField">
                @Html.Hidden("UserId", User.Identity.Name, new { @class = "UserID", name = "UserId" })
            </div>
        }
    </div>

</div>


@section scripts{
    <script src="~/Scripts/RMS/OrderOnline.js"></script>

}

Rms-Core-313/Rms-Core-313/Views/OnlineOrder/GetOrderList.cshtml
@using Microsoft.AspNetCore.Identity

@model Rms_Core_313.Models.Vm.OrderPlaceVm
@{
    ViewData["Title"] = "GetOrderList";
    Layout = "~/Views/Shared/_LayoutDashvoard.cshtml";
}

<h1 style="text-align:center">Order List</h1>

<div class="row center">
    <div class="container" style="margin-left:5%">

        <div class="col-lg-10" style="margin-left:0">

            <table class="table table-striped row">

                <tr>

                    <th>Sl</th>
                    <th>Order Id</th>

                    <th>User Id</th>
                    <th>Phone</th>
                    <th>Order Date</th>
                    <th>Payment </th>
                    <th class="col-2">Dish Name</th>
                    <th>Total Quantity</th>
                    <th>Total Price</th>
                    <th>Action</th>
                </tr>


                @{int sl = 1; }
                @foreach (var i in Model.OrderPlaces)
                {
                    <tr>
                        <td>@(sl++ )</td>
                        <td>
                            @i.Id

                        </td>
                        <td>
                            @i.UserId

                        </td>
                        <td>
                            @i.ReciverPhone

                        </td>
                        <td>@i.date</td>
                        <td>
                            @if (i.IsCashOnDelivery == "on")
                            {
                                <h6>Cash on delivery</h6>
                            }
                            else
                            {

                                <h6>Srtipes </h6>
                            }
                        </td>

                        <td>
                            @foreach (var item in i.OrderPlaceDetails)
                            {

                                @item.menusCreate.Name;<br />

                            }

                        </td>
                        <td>
                            @{var dataQ = 0;}
                            @foreach (var item in i.OrderPlaceDetails)
                            {

                                dataQ += item.Quantity;
                            }
                            @dataQ
                        </td>
                        <td>
                            @{var dataprice = 0.00;}
                            @foreach (var item in i.OrderPlaceDetails)
                            {

                                dataprice += item.Price;
                            }
                            @dataprice
                        </td>


                        <td>
                            @if (i.IsInKichen == false)
                            {
                                <button class="btn btn-success Kitchen" style="font-size:small" data-orderID=" @i.Id" name="Name">Kitchen</button>

                            }
                            else if (i.IsDelivering == false)
                            {
                                <button class="btn btn-primary Delivering" style="font-size:small" data-orderID=" @i.Id" name="Name">Delivering</button>
                            }
                            else if (i.IsRecived == true)
                            {

                                <h6 style="color:forestgreen">Delivered</h6>
                            }
                            else
                            {
                                <h6 class="text-info">Delivering </h6>
                            }
                        </td>

                    </tr>
                }


            </table>
        </div>

    </div>


</div>


@section scripts{
    <script src="~/Scripts/RMS/OrderOnline.js"></script>

}

Rms-Core-313/Rms-Core-313/Views/OnlineOrder/PaymentGetwayFeedback.cshtml
@{
    ViewData["Title"] = "PaymentGetwayFeedback";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <br />
    <br />
    <br />
<h3 style="margin-top:10%;text-align:center">Thank you for your payment! You will get a mail soon!</h3>

Rms-Core-313/Rms-Core-313/Views/OnlineOrder/PaymentGetwayIntegrate.cshtml
@using Microsoft.Extensions.Options
@inject IOptions<Rms_Core_313.Models.StripeSetting> Stripe
@model Rms_Core_313.Models.StripeSetting
@{
    ViewData["Title"] = "PaymentGetwayIntegrate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <h3 style="margin-top:10%;text-align:center" >Complite Your Payment</h3>

    <div class="text-center">
        <form asp-controller="OnlineOrder" asp-action="PaymentGetwayIntegrate" method="post">
            <article>
                <label>
                    Amount:£ @Model.Amount
                </label>
            </article>
            <script src="//checkout.stripe.com/v2/checkout.js"
                    class="stripe-button"
                    data-key="@Stripe.Value.Publishablekey"
                    data-locale="auto"
                    data-description="Sample Charge"
                    data-amount="@(Model.Amount * 100)">
            </script>
        </form>
    </div>