Rms-Core-313/Rms-Core-313/Controllers/MenuCreateController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Rms_Core_313.BLL.Interface;
using Rms_Core_313.Model.Models;
using Rms_Core_313.Models;
using Rms_Core_313.Models.Vm;

namespace Rms_Core_313.Controllers
{
    public class MenuCreateController : Controller
    {
        private readonly IMenuCreateManager manager;
        private readonly IMapper _mapper;
        private readonly IWebHostEnvironment webHostEnvironment;
        public MenuCreateController(IMenuCreateManager _manager, IMapper mapper, IWebHostEnvironment hostEnvironment)
        {
            manager = _manager;
            _mapper = mapper;
            webHostEnvironment = hostEnvironment;
        }


        public ActionResult Create()
        {
            MenuCreateVm menu = new MenuCreateVm();
            menu.TypeList = manager.GetMenuType().Select(c => new SelectListItem()
            {
                Value = c.Id.ToString(),
                Text = c.Name
            }).ToList();
            return View(menu);
        }
        [HttpPost]
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Create(MenuCreateVm menu)
        {
           
            if (ModelState.IsValid)
            {

                using (MemoryStream stream = new MemoryStream())
                {
                    await menu.Images.CopyToAsync(stream);
                    menu.Data = stream.ToArray();
                }
               
            }
           var entity = _mapper.Map<MenusCreate>(menu);
           var data = manager.Create(entity);
           menu.TypeList = manager.GetMenuType().Select(c => new SelectListItem()
           {
               Value = c.Id.ToString(),
               Text = c.Name
           }).ToList();
            return RedirectToAction("GetMenuList");
        }
        private string UploadedFile(MenuCreateVm model)
        {
            string uniqueFileName = null;

            if (model.Images != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Images.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.Images.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }
        [Authorize(Roles = "SuperAdmin")]
        public ActionResult GetMenuList()
        {
            var entity = new MenuCreateVm();
            entity.Menus = manager.GetMenuList();
            return View(entity);
        }
        public PartialViewResult GetMenuListByType(int id)
        {
            var entity = new MenuCreateVm();
            entity.Menus = manager.GetMenuListByType(id);
            return PartialView("~/Views/Shared/_MainDataForOnlineOrder.cshtml", entity);
        }
        public PartialViewResult GetAllMenuList()
        {
            var entity = new MenuCreateVm();
            entity.Menus = manager.GetMenuListByType();
            return PartialView("~/Views/Shared/_MainDataForOnlineOrder.cshtml", entity);
        }
        [Authorize(Roles = "SuperAdmin")]
        public ActionResult CreateType()
        {
            return View();
        }
        [Authorize(Roles = "SuperAdmin")]
        [HttpPost]
        public ActionResult CreateType(CreateTypeVm vm)
        {
            var entity = _mapper.Map<CreateType>(vm);
            manager.CreateType(entity);
            return RedirectToAction("Create");
        }
       
        [Authorize(Roles = "SuperAdmin")]
        public ActionResult Delete(int id)
        {
            MenuCreateVm vm = new MenuCreateVm();
            vm.Id = id;
            var entity = _mapper.Map<MenusCreate>(vm); 
            manager.Delete(entity);
            return RedirectToAction("GetMenuList");
        }
        public async Task<JsonResult> CheckActivity(MenuCreateVm Vm)
        {
            if (Vm.Id != null)
            {
                 var rData = manager.UpdateActivity(Vm.Id);
                return Json(rData);
            }
            return Json(false);
        }
        public async Task<JsonResult> GetTypes()
        {
            var data = manager.GetMenuType();
            return Json(data);
        }
    }
}

Rms-Core-313/Rms-Core-313/Views/MenuCreate/Create.cshtml
@model Rms_Core_313.Models.MenuCreateVm
@{
    Layout = "~/Views/Shared/_LayoutDashvoard.cshtml";
}
@using (Html.BeginForm("Create", "MenuCreate", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
@Html.AntiForgeryToken()
<h4>Create a new Menu</h4>
<hr />
@Html.ValidationSummary("", new { @class = "text-danger" })
<div class="form-group">
    @Html.LabelFor(m => m.Name, new { @class = "col-md-3 control-label" })
    <div class="col-md-5">
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control border border-primary" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(m => m.CreateTypeId, new { @class = "col-md-3 control-label" })
    <div class="col-md-5">
        @Html.DropDownListFor(m => m.CreateTypeId, Model.TypeList, new { @class = "form-control dd-type" })

    </div>
</div>
<div class="form-group">
    @Html.LabelFor(m => m.Price, new { @class = "col-md-3 control-label" })
    <div class="col-md-5">
        @Html.TextBoxFor(m => m.Price, new { @class = "form-control border border-primary" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(m => m.Discriptions, new { @class = "col-md-3 control-label" })
    <div class="col-md-5">
        @Html.TextBoxFor(m => m.Discriptions, new { @class = "form-control border border-primary" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(m => m.Data, new { @class = "col-md-3 control-label" })
    <div class="col-md-5">
        <input class="form-control" type="file" name="Images" onchange="fileCheck(this);" />

    </div>
</div>


<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" class="btn btn-default border border-primary" value="Add" />
    </div>
</div>
}

@section Scripts {

    <script src="~/Scripts/jquery.validate.js"></script>

    <script type="text/javascript">

        function fileCheck(obj) {
            var fileExtension = ['jpeg', 'jpg', 'png', 'gif', 'bmp'];
            if ($.inArray($(obj).val().split('.').pop().toLowerCase(), fileExtension) == -1) {
                alert("Only '.jpeg','.jpg', '.png', '.gif', '.bmp' formats are allowed.");
            }
            else {
                alert("Done");
            }

        }
    </script>
}

Rms-Core-313/Rms-Core-313/Views/MenuCreate/CreateType.cshtml
@model Rms_Core_313.Models.Vm.CreateTypeVm
@{
    Layout = "~/Views/Shared/_LayoutDashvoard.cshtml";
}

<h2>CreateType</h2>
@using (Html.BeginForm("CreateType", "MenuCreate", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-md-3 control-label" })
        <div class="col-md-5">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control border border-primary" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default border border-primary" value="Add" />
        </div>
    </div>

}
@section Scripts {
    <script src="~/Scripts/jquery.validate.js"></script>

    <script type="text/javascript">

        function fileCheck(obj) {
            var fileExtension = ['jpeg', 'jpg', 'png', 'gif', 'bmp'];
            if ($.inArray($(obj).val().split('.').pop().toLowerCase(), fileExtension) == -1) {
                alert("Only '.jpeg','.jpg', '.png', '.gif', '.bmp' formats are allowed.");
            }
            else {
                alert("Done");
            }

        }
    </script>
}

Rms-Core-313/Rms-Core-313/Views/MenuCreate/GetMenuList.cshtml
@model Rms_Core_313.Models.MenuCreateVm
@{
    ViewBag.Title = "GetMenuList";
    Layout = "~/Views/Shared/_LayoutDashvoard.cshtml";
}

<h2>Menu List</h2>


<div class="row center">
    <div class="container" style="margin-left:5%">

        <div class="col-lg-10" style="margin-left:0">

            <table class="table table-striped row">

                <tr>

                    <th>Sl</th>
                    <th>Photo</th>
                    <th>Food Name</th>
                    <th>Price</th>
                    <th>Discriptions</th>
                    <th>Food Type</th>

                    <th>Active</th>
                    <th>Action</th>
                </tr>


                @{int sl = 1; }
                @foreach (var i in Model.Menus)
                {
                    <tr>
                        <td>@(sl++ )</td>
                        <td>

                            @if (i.Data != null)
                            {
                                var base64 = Convert.ToBase64String(i.Data);
                                var imgsrc = string.Format("data:image/png;base64,{0}", base64);
                                <img src='@imgsrc' style="max-width:100px;max-height:100px" />
                            }
                            else
                            {
                                <img src='~/images/No-Image-Available.jpg' style="max-width:100px;max-height:100px" />
                            }
                        </td>
                        <td>@i.Name</td>
                        <td>@i.Price</td>
                        <td>@i.Discriptions</td>
                        <td>@i.CreateType.Name</td>

                        <td>
                            @if (i.Active)
                            {
                                <input type="checkbox" checked="checked" class="checkbox" id="@i.Id">
                            }
                            else
                            {
                                <input type="checkbox" class="checkbox" id="@i.Id">
                            }



                        </td>
                        <td>

                            <a href="~/MenuCreate/Delete?id=@i.Id" class="btn btn-danger" style="font-size:small" name="Name">Remove</a>
                        </td>
                    </tr>
                }


            </table>
        </div>

    </div>


</div>
@section Scripts {
    <script src="~/Scripts/RMS/MenuList.js"></script>
   
}